import { useEffect, useState } from "react";
import { FileText } from "lucide-react";
import { GlassCard } from "../components/ui/GlassCard";
import { LoadingState, EmptyState } from "../components/ui/Feedback";
import { listRequirementItems } from "../services/agentInsightsApi";
import type { RequirementItem } from "../types";
import { cn } from "../lib/cn";

const PRIORITY_COLOR: Record<string, string> = {
  low: "text-brand-dark/50",
  medium: "text-amber-300",
  high: "text-orange-300",
};

export function RequirementsPage() {
  const [items, setItems] = useState<RequirementItem[] | null>(null);
  const [filter, setFilter] = useState<"all" | "functional" | "non-functional">("all");

  useEffect(() => {
    listRequirementItems().then(setItems);
  }, []);

  const filtered = items?.filter((i) => filter === "all" || i.type === filter);

  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="text-2xl font-medium tracking-tight sm:text-3xl">Requirements Workspace</h1>
        <p className="mt-1 text-brand-dark/50">Structured specifications generated by your Requirements Agent.</p>
      </div>

      <div className="flex gap-2">
        {(["all", "functional", "non-functional"] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={cn(
              "rounded-full border px-3.5 py-1.5 text-sm capitalize transition-colors",
              filter === f ? "border-brand-dark/20 bg-brand-dark/5 text-brand-dark" : "border-brand-dark/10 bg-brand-light text-brand-dark/50 hover:text-brand-dark"
            )}
          >
            {f.replace("-", " ")}
          </button>
        ))}
      </div>

      {!filtered ? (
        <LoadingState label="Loading requirements…" />
      ) : filtered.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="No requirements yet"
          description="Ask the Requirements Agent to spec out a feature and items will show up here."
        />
      ) : (
        <div className="flex flex-col gap-3">
          {filtered.map((item) => (
            <GlassCard key={item.id} hover padding="md" className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div className="flex items-start gap-3">
                <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-brand-dark/10 bg-brand-light">
                  <FileText className="h-4 w-4 text-brand-dark/60" />
                </span>
                <div>
                  <p className="text-xs font-medium text-brand-dark/40">{item.sourceConversationTitle}</p>
                  <p className="text-sm text-brand-dark/80">{item.text}</p>
                </div>
              </div>
              <div className="flex items-center gap-3 pl-12 sm:pl-0">
                <span className={cn("text-xs font-medium capitalize", PRIORITY_COLOR[item.priority] ?? "text-brand-dark/70")}>
                  {item.priority} priority
                </span>
              </div>
            </GlassCard>
          ))}
        </div>
      )}
    </div>
  );
}
